from typing import Optional, Protocol
from .entities import Person, Organization

class ScraperPort(Protocol):
    async def search_directors(self, query: str, limit: int = 100) -> list[Person]: ...
    async def get_person_organizations(self, person: Person, limit: int = 100) -> list[Organization]: ...

class ProxyPort(Protocol):
    async def get_proxy(self) -> Optional[str]: ...

class MessageBrokerPort(Protocol):
    async def publish_to_kafka(self, topic: str, message: dict) -> None: ...
    async def publish_to_rmq(self, queue: str, message: dict) -> None: ...
